# Generated by Django 5.2.6 on 2025-09-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='id_autor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='id_editorial', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='id_miembro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_membresia', models.DateField()),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='id_libro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('anio_publicacion', models.IntegerField()),
                ('autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.CASCADE, to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='id_editorial', on_delete=django.db.models.deletion.CASCADE, to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='id_prestamo', primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.CASCADE, to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='id_miembro', on_delete=django.db.models.deletion.CASCADE, to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'prestamo',
            },
        ),
    ]
